spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/vaccine?createDatabaseIfNotExist=true
    username: root
    password: 2115
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    baseline-on-migrate: true


flyway:
  schemas: vaccine
  defaultSchema: vaccine
